// <auto-generated />
using System;
using APIGol.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIGol.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200221143004_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIGol.Models.Airplane", b =>
                {
                    b.Property<int>("AviaoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodAviao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("DtRegistro");

                    b.Property<string>("Modelo")
                        .HasMaxLength(150);

                    b.Property<int>("QtdPassageiro");

                    b.HasKey("AviaoId");

                    b.ToTable("Airplanes");
                });
#pragma warning restore 612, 618
        }
    }
}
